#include "src\app_RM_connect.c"
#include "src\app_RM_fun.c"
#include "src\app_RM_interface.c"
#include "src\app_RM_IEC1107.c"
#include "src\app_RM_CheckTime.c"
#include "src\app_RM_FLverify.c"
#include "src\app_RM_XLverify.c"
#include "src\app_RM_SZverify.c"
//#include "src\app_RM_XNFZ.c"
#include "src\app_RM_search.c"

