#include"src\GUI_lcd_driver.h"
#include"src\Front\GUI_libext.c"
#include"src\Front\GUI_liblocal.c"
#include"src\Gui_front_connect.c"
#include"src\Gui_lcd_connect.c"
#include"src\Gui_core.c"
#include"src\Gui_widget.c"
#include"src\Gui_cursor.c"
#include"src\Gui_touch.c"
#include"src\GUI_lcd_driver.c"
#include"src\GUI_mem.c"
#include"src\GUI_str.c"
#include"src\GUI_hook.c"
#include"src\GUI_Polygon.c"
#include"src\GUI_arrow.c"
#include"src\GUI_circle.c"
#include"src\GUI_Memdev.c"
//#include"src\GUI_Msg.c"
#include"src\GUI_OS.c"


